name: build_meta_image

on:
  push:
    paths:
      - 'docker/Metafile'
      - 'docker/Metafile.alpine'
      - 'requirements.txt'
    branches:
      - "dev"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Environment Variables
        run: |
          IMG=fulltclash
          echo "IMG=${IMG}" >> $GITHUB_ENV
          echo "IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${IMG}" >> $GITHUB_ENV
      - name: Build Debian Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Metafile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}:debian
      - name: Build Alpine Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Metafile.alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}:alpine
